# Example Dockerfile to showcase possibilities of prepping a dev container
# This file can be customized to include anything you would need on your Linux installation.

ARG NUKE_VERSION=15.0
FROM "ghcr.io/gillesvink/nukedockerbuild:${NUKE_VERSION}-linux-latest"
RUN dnf install -y git